### ISSUE TITLE
singleton_test error

### ISSUE THREAD

**Issue by dvof** [pal-robotics/dynamic_introspection#2]
I'm trying to build the Tiago simulation for Ros kinetic but I'm getting an error,

`Linking CXX executable /home/daan/tiago_public_ws/devel/lib/dynamic_introspection/singleton_test
c++: error: backward: No such file or directory
dynamic_introspection/test/CMakeFiles/singleton_test.dir/build.make:130: recipe for target '/home/daan/tiago_public_ws/devel/lib/dynamic_introspection/singleton_test' failed` 

Does anyone know what might fix this issue?

**Comment by v-lopez** [comment]
Do you have backward_ros in your workspace?

Also please git pull this repo, we just pushed a fix for the build dependency ordering.

**Comment by dvof** [comment]
Fixed it!
Before I used `catkin_make` which resulted in this issue, when I used `catkin build` the pal_hardware_gazebo package turned out to be the problem.
I git pulled that repo and it resolved the issue.

Thanks anyways v-lopez for responding so quickly.
